Repository lqthang2204/BDDDevicesAutomation, pull requests merged in 2023-07, with the labels that each got.

#11 Improve function read file yaml config before run test
  .gitignore
  Configuration/configuration_env.py
  Configuration/devices.py
  Configuration/stage.py
  Utilities/action_android.py
  Utilities/action_web.py
  Utilities/common.py
  Utilities/env_android.py
  Utilities/read_configuration.py
  config_env.ini
  environments.yml
  features/Login.feature
  features/MobileFeature/Login.feature
  features/MobileFeature/idiva.feature
  features/MobileFeature/tiki.feature
  features/environment.py
  features/orangeHRM-2.feature
  features/orangeHRM.feature
  features/steps/execure_script.py
  features/techpanda.feature
  output/outputs/logs/4f84aa650333a5edaf51c792050e900acb6cd38bc1ac269977ce6f064ef0e455_1/scenario.log
  requirements.txt
  resources/pages/General/Common.yaml
  resources/pages/google/pageGoogle.yaml
  resources/pages/idiva/Home_idiva.yaml
  resources/pages/idiva/product_sneaker.yaml
  resources/pages/orangeHRM/LoginPage.yaml
  resources/pages/tiki/indexTiki.yaml
Labels: documentation

#13 write log for web and mobile
  .github/workflows/python-package-paralle-with-tagsl.yml
  .github/workflows/python-package-parallel.yml
  Utilities/action_android.py
  Utilities/action_web.py
  features/Login.feature
  features/MobileFeature/Login.feature
  features/MobileFeature/idiva.feature
  features/MobileFeature/tiki-mobile.feature
  features/environment.py
  features/orangeHRM-2.feature
  features/orangeHRM.feature
  features/techpanda.feature
Labels: enhancement

#14 add more script open application
  environments.yml
  features/MobileFeature/idiva.feature
  features/MobileFeature/tiki-mobile.feature
  features/steps/execure_script.py
  resources/pages/tiki/HomeTiki.yaml
Labels: documentation, enhancement

#17 fix issue steps-unimplemented
  features/Login.feature
  features/steps/execure_script.py
Labels: bug

#20 Command line interface using click package
  .github/workflows/project-runner.yml
  ManagementElements/ActionElements.py
  ManagementElements/ActionTest.py
  ManagementElements/Elements.py
  ManagementElements/Locator.py
  ManagementElements/Page.py
  README.md
  Utilities/action_android.py
  Utilities/action_web.py
  Utilities/common.py
  Utilities/env_android.py
  Utilities/read_configuration.py
  config_env.ini
  environments.yml
  features/environment.py
  features/steps/execure_script.py
  launch/RunTest.py
  project_runner.py
  requirements.txt
Labels: in-progress

#21 develop function wait with DataTable - WEB
  Utilities/action_web.py
  features/Login.feature
  features/steps/execure_script.py
  resources/pages/orangeHRM/LoginPage.yaml
Labels: in-progress, web-env
