Repository lqthang2204/BDDDevicesAutomation, pull requests merged in 2023-08, with the labels that each got.

#36 Add more config execute remote with Saucelabs
  Configuration/api_facets.py
  Configuration/stage.py
  Utilities/action_web.py
  Utilities/read_configuration.py
  config_env.ini
  environments.yml
  features/environment.py
  features/scenarios/mobile/Login.feature
  features/scenarios/mobile/idiva.feature
  features/scenarios/web/Login.feature
  features/scenarios/web/orangeHRM-2.feature
  features/scenarios/web/orangeHRM.feature
  features/scenarios/web/techpanda.feature
  features/steps/execure_script.py
  remote_config.ini
Labels: enhancement

#37 Library code Refactored and optimized. More BDD samples added
  .github/workflows/project-runner.yml
  Utilities/action_web.py
  features/environment.py
  features/scenarios/samples/Compare_Operation.feature
  features/scenarios/samples/DateTime.feature
  features/scenarios/web/Login.feature
  features/scenarios/web/techpanda.feature
  features/steps/common_stepdefs.py
  features/steps/execure_script.py
  libraries/data_generators.py
  libraries/misc_operations.py
  libraries/number_string_operations.py
  tags_expr_processor.py
Labels: enhancement

#40 Automated Web Accessibility Testing using AXE package
  .gitignore
  Utilities/accessibility_report.py
  features/environment.py
  features/scenarios/web/Login.feature
  features/scenarios/web/orangeHRM.feature
  features/steps/common_stepdefs.py
  requirements.txt
  resources/accessibility/AXE_Main_Template.html
Labels: enhancement

#41 Remove setter getter change page spec
  Configuration/api_facets.py
  Configuration/configuration_env.py
  Configuration/devices.py
  Configuration/stage.py
  ManagementElements/ActionElements.py
  ManagementElements/ActionTest.py
  ManagementElements/Elements.py
  ManagementElements/Locator.py
  ManagementElements/Page.py
  Utilities/action_android.py
  Utilities/action_web.py
  Utilities/common_ui.py
  Utilities/read_configuration.py
  features/environment.py
  features/scenarios/web/Login.feature
  features/steps/execure_script.py
  resources/pages/orangeHRM/LoginPage.yaml
Labels: documentation

#43 Feature/descriptive logger
  .github/workflows/project-runner-check-api.yml
  .github/workflows/project-runner.yml
  Utilities/action_android.py
  Utilities/action_web.py
  Utilities/common_ui.py
  Utilities/read_configuration.py
  features/environment.py
  features/scenarios/api/fake_rest_api.feature
  features/scenarios/mobile/idiva.feature
  features/scenarios/web/Login.feature
  features/scenarios/web/orangeHRM.feature
  features/steps/api_stepdefs.py
  features/steps/common_stepdefs.py
  features/steps/execure_script.py
  libraries/accessibility_report.py
  libraries/api/api_asserts.py
  libraries/api/api_sanitizer.py
  libraries/api/request_core.py
  libraries/data_generators.py
  libraries/faker/User.py
  libraries/faker/management_user.py
  libraries/logger_core.py
  libraries/misc_operations.py
  project_runner.py
  resources/api/request-json/user_gorest.json
  resources/pages/idiva/Home_idiva.yaml
Labels: enhancement

#44 Develop feature verify element with datatable
  Utilities/action_android.py
  Utilities/common_ui.py
  environments.yml
  features/environment.py
  features/scenarios/mobile/app-clock.feature
  features/scenarios/web/IgnoredFile.feature
  features/steps/execure_script.py
  libraries/api/api_asserts.py
  libraries/data_generators.py
  libraries/logger_core.py
  resources/pages/app_clock/alarm_page.yaml
  resources/pages/app_clock/clock_page.yaml
Labels: documentation, in-progress
